[04/Oct/2014 20:55:22] ERROR [django.request:231] Internal Server Error: /admin/core/notice/
Traceback (most recent call last):
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 567, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 204, in inner
    return view(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1576, in changelist_view
    selection_note=_('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: ERRO:  coluna core_notice.author_id não existe
LINE 1: ... FROM "core_notice" INNER JOIN "core_author" ON ( "core_noti...
                                                             ^

[04/Oct/2014 20:55:25] ERROR [django.request:231] Internal Server Error: /admin/core/notice/
Traceback (most recent call last):
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 567, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 204, in inner
    return view(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1576, in changelist_view
    selection_note=_('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/wendell/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: ERRO:  coluna core_notice.author_id não existe
LINE 1: ... FROM "core_notice" INNER JOIN "core_author" ON ( "core_noti...
                                                             ^

[04/Oct/2014 20:55:28] WARNING [django.request:143] Not Found: /favicon.ico
[04/Oct/2014 20:58:52] WARNING [django.request:143] Not Found: /pma/scripts/setup.php
[04/Oct/2014 20:59:54] WARNING [django.request:143] Not Found: /favicon.ico
[04/Oct/2014 21:00:16] WARNING [django.request:143] Not Found: /favicon.ico
