[20/Apr/2014 22:42:37] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 22:42:48] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 22:56:41] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 22:58:27] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:01:55] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:02:11] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:04:03] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:04:32] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:06:11] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:11:15] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:13:19] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:14:23] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:22:20] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:23:22] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:24:43] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:25:59] ERROR [fotec.apps.core.views:169] Template not found! Raised: Invalid filter: 'strip_tags'
[20/Apr/2014 23:25:59] ERROR [fotec.apps.core.views:169] Template not found! Raised: nonajax/gui.html
[20/Apr/2014 23:25:59] ERROR [fotec.apps.core.views:169] Template not found! Raised: nonajax/home.html
[20/Apr/2014 23:25:59] INFO [fotec.apps.core.views:175] Not found available templates, loading 404 template!
[20/Apr/2014 23:28:12] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:28:32] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:29:18] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:29:30] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:29:36] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[20/Apr/2014 23:29:51] ERROR [fotec.apps.core.views:169] Template not found! Raised: Invalid filter: 'capitalize'
[20/Apr/2014 23:29:51] ERROR [fotec.apps.core.views:169] Template not found! Raised: nonajax/gui.html
[20/Apr/2014 23:29:51] ERROR [fotec.apps.core.views:169] Template not found! Raised: nonajax/home.html
[20/Apr/2014 23:29:51] INFO [fotec.apps.core.views:175] Not found available templates, loading 404 template!
[20/Apr/2014 23:30:02] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:13:41] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:14:05] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:14:24] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:16:04] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:18:25] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:18:32] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:27:16] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:27:48] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:28:14] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:29:41] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:29:58] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:30:14] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:30:38] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:30:41] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:30:51] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:32:34] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 00:32:42] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 13:22:12] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 13:22:34] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 16:42:01] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 22:28:11] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 22:28:24] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 22:29:23] WARNING [django.request:145] Not Found: /favicon.ico
[21/Apr/2014 22:29:44] INFO [fotec.apps.core.models:354] New matching query does not exist.
[21/Apr/2014 22:29:44] INFO [fotec.apps.core.models:297] TeSTE
[21/Apr/2014 22:30:17] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[21/Apr/2014 22:30:52] WARNING [django.request:145] Not Found: /favicon.ico
[21/Apr/2014 22:31:00] INFO [fotec.apps.core.models:297] TeSTE
[21/Apr/2014 22:31:00] ERROR [fotec.apps.core.models:298] TeSTE
[21/Apr/2014 22:31:00] WARNING [fotec.apps.core.models:299] TeSTE
[22/Apr/2014 18:50:47] INFO [fotec.apps.core.views:171] Template loaded: gui/nonajax/home.html
[22/Apr/2014 21:41:42] ERROR [fotec.apps.core.views:169] Template not found! Raised: gui/nonajax/home.html
[22/Apr/2014 21:41:42] ERROR [fotec.apps.core.views:169] Template not found! Raised: nonajax/gui.html
[22/Apr/2014 21:41:42] ERROR [fotec.apps.core.views:169] Template not found! Raised: nonajax/home.html
[22/Apr/2014 21:41:42] INFO [fotec.apps.core.views:175] Not found available templates, loading 404 template!
[22/Apr/2014 21:41:42] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 21:42:24] INFO [fotec.apps.core.views:171] Template loaded: gui/home.html
[22/Apr/2014 21:43:01] INFO [fotec.apps.core.views:171] Template loaded: gui/home.html
[22/Apr/2014 21:51:23] INFO [fotec.apps.core.views:171] Template loaded: gui/home.html
[22/Apr/2014 21:54:38] INFO [fotec.apps.core.views:171] Template loaded: gui/home.html
[22/Apr/2014 21:55:10] INFO [fotec.apps.core.views:171] Template loaded: gui/home.html
[22/Apr/2014 21:55:26] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 21:56:21] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:02:22] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:03:25] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:03:59] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:04:08] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:06:45] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:06:58] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:07:28] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:08:31] INFO [fotec.apps.core.views:171] Template loaded: gui/news.html
[22/Apr/2014 22:09:35] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:09:40] WARNING [django.request:145] Not Found: /Users/wendellpbarreto/Projects/python/fotec/media/upload/[poiuy453.png
[22/Apr/2014 22:24:36] ERROR [django.request:226] Internal Server Error: /news/5
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/urls.py", line 9, in <module>
    from fotec.apps.gui.views import GUI
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/gui/views.py", line 44
    return {
         ^
SyntaxError: invalid syntax
[22/Apr/2014 22:24:37] ERROR [django.request:226] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/urls.py", line 9, in <module>
    from fotec.apps.gui.views import GUI
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/gui/views.py", line 44
    return {
         ^
SyntaxError: invalid syntax
[22/Apr/2014 22:24:44] ERROR [django.request:226] Internal Server Error: /
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/urls.py", line 9, in <module>
    from fotec.apps.gui.views import GUI
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/gui/views.py", line 44
    return {
         ^
SyntaxError: invalid syntax
[22/Apr/2014 22:24:44] ERROR [django.request:226] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/urls.py", line 9, in <module>
    from fotec.apps.gui.views import GUI
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/gui/views.py", line 44
    return {
         ^
SyntaxError: invalid syntax
[22/Apr/2014 22:27:02] ERROR [django.request:226] Internal Server Error: /
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/urls.py", line 9, in <module>
    from fotec.apps.gui.views import GUI
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/gui/views.py", line 48
    else:
       ^
SyntaxError: invalid syntax
[22/Apr/2014 22:27:02] ERROR [django.request:226] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/urls.py", line 9, in <module>
    from fotec.apps.gui.views import GUI
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/gui/views.py", line 48
    else:
       ^
SyntaxError: invalid syntax
[22/Apr/2014 22:28:19] INFO [fotec.apps.core.views:171] Template loaded: gui/home.html
[22/Apr/2014 22:28:43] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:29:10] INFO [fotec.apps.core.models:353] Notice matching query does not exist.
[22/Apr/2014 22:29:10] ERROR [django.request:226] Internal Server Error: /admin/core/notice/add/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1131, in add_view
    self.save_model(request, new_object, form, False)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 860, in save_model
    obj.save()
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/core/models.py", line 360, in notices_save_decorator
    create_resized_photos(sender, instance)
  File "/Users/wendellpbarreto/Projects/python/fotec/fotec/apps/core/models.py", line 84, in create_resized_photos
    big = Image.notice("RGBA", (conf["big"]["w"], conf["big"]["h"]), default_color)
AttributeError: 'module' object has no attribute 'notice'
[22/Apr/2014 22:29:43] INFO [fotec.apps.core.models:353] Notice matching query does not exist.
[22/Apr/2014 22:29:44] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:29:47] INFO [fotec.apps.core.views:171] Template loaded: gui/home.html
[22/Apr/2014 22:29:56] ERROR [fotec.apps.core.views:169] Template not found! Raised: gui/notices.html
[22/Apr/2014 22:29:56] ERROR [fotec.apps.core.views:169] Template not found! Raised: gui.html
[22/Apr/2014 22:29:56] ERROR [fotec.apps.core.views:169] Template not found! Raised: gui/notices.html
[22/Apr/2014 22:29:56] INFO [fotec.apps.core.views:175] Not found available templates, loading 404 template!
[22/Apr/2014 22:29:56] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:30:20] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:40:04] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:40:07] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:40:25] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:40:37] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:42:27] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:42:43] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:46:31] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:46:48] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:46:51] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:47:14] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:47:29] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:52:45] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:52:57] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:53:23] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:53:41] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:54:33] INFO [fotec.apps.core.views:171] Template loaded: gui/notice.html
[22/Apr/2014 22:56:39] WARNING [django.request:145] Not Found: /admin/core/new/4/
[22/Apr/2014 22:56:40] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:56:47] WARNING [django.request:145] Not Found: /admin/core/new/4=1/
[22/Apr/2014 22:56:50] WARNING [django.request:145] Not Found: /admin/core/new/1/
[22/Apr/2014 22:56:57] ERROR [django.request:226] Internal Server Error: /admin/core/notice/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1411, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 782, in execute_sql
    cursor.execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column core_notice.views does not exist
LINE 1: SELECT "core_notice"."id", "core_notice"."views", "core_noti...
                                   ^

[22/Apr/2014 22:57:11] ERROR [django.request:226] Internal Server Error: /admin/core/notice/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1411, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 782, in execute_sql
    cursor.execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column core_notice.views does not exist
LINE 1: SELECT "core_notice"."id", "core_notice"."views", "core_noti...
                                   ^

[22/Apr/2014 22:57:15] ERROR [django.request:226] Internal Server Error: /admin/core/notice/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1411, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 782, in execute_sql
    cursor.execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column core_notice.views does not exist
LINE 1: SELECT "core_notice"."id", "core_notice"."views", "core_noti...
                                   ^

[22/Apr/2014 22:57:16] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:57:41] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:57:52] ERROR [django.request:226] Internal Server Error: /admin/core/notice/add/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1161, in add_view
    media = self.media + adminForm.media
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 65, in _media
    for fs in self:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 46, in __iter__
    **options
TypeError: type object got multiple values for keyword argument 'readonly_fields'
[22/Apr/2014 22:57:53] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:58:10] ERROR [django.request:226] Internal Server Error: /admin/core/notice/add/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1161, in add_view
    media = self.media + adminForm.media
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 65, in _media
    for fs in self:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 46, in __iter__
    **options
TypeError: type object got multiple values for keyword argument 'readonly_fields'
[22/Apr/2014 22:58:10] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:58:31] ERROR [django.request:226] Internal Server Error: /admin/core/notice/add/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1161, in add_view
    media = self.media + adminForm.media
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 65, in _media
    for fs in self:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 46, in __iter__
    **options
TypeError: type object got multiple values for keyword argument 'readonly_fields'
[22/Apr/2014 22:58:31] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 22:58:32] ERROR [django.request:226] Internal Server Error: /admin/core/notice/add/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1161, in add_view
    media = self.media + adminForm.media
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 65, in _media
    for fs in self:
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 46, in __iter__
    **options
TypeError: type object got multiple values for keyword argument 'readonly_fields'
[22/Apr/2014 23:00:40] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 23:00:42] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 23:01:16] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 23:01:40] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 23:01:54] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 23:02:29] ERROR [django.request:226] Internal Server Error: /admin/core/notice/add/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1108, in add_view
    ModelForm = self.get_form(request)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 531, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (likes, comments) specified for Notice. Check fields/fieldsets/exclude attributes of class NoticeAdmin.
[22/Apr/2014 23:02:30] WARNING [django.request:145] Not Found: /favicon.ico
[22/Apr/2014 23:02:42] ERROR [django.request:226] Internal Server Error: /admin/core/notice/add/
Traceback (most recent call last):
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1108, in add_view
    ModelForm = self.get_form(request)
  File "/Users/wendellpbarreto/.virtualenvs/fotec/lib/python2.7/site-packages/django/contrib/admin/options.py", line 531, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (likes, comments) specified for Notice. Check fields/fieldsets/exclude attributes of class NoticeAdmin.
[22/Apr/2014 23:02:42] WARNING [django.request:145] Not Found: /favicon.ico
